/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_vgaw_rtmptest1_RTMPClient
#define _Included_com_vgaw_rtmptest1_RTMPClient
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_Your_package_name_RTMPClient_connect
  (JNIEnv *, jobject, jstring);

JNIEXPORT void JNICALL Java_Your_package_name_RTMPClient_disconnect
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_Your_package_name_RTMPClient_writeH264RawFrame
  (JNIEnv *, jobject, jbyteArray, jint, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
