/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_ossrs_yasea_flv_SrsFlv */

#ifndef _Included_net_ossrs_yasea_flv_SrsFlv
#define _Included_net_ossrs_yasea_flv_SrsFlv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_ossrs_yasea_flv_SrsFlv
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_ossrs_yasea_flv_SrsFlv_reset
  (JNIEnv *, jobject);

/*
 * Class:     net_ossrs_yasea_flv_SrsFlv
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_ossrs_yasea_flv_SrsFlv_stop
  (JNIEnv *, jobject);

/*
 * Class:     net_ossrs_yasea_flv_SrsFlv
 * Method:    setVideoTrack
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_ossrs_yasea_flv_SrsFlv_setVideoTrack
  (JNIEnv *, jobject);

/*
 * Class:     net_ossrs_yasea_flv_SrsFlv
 * Method:    setAudioTrack
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_ossrs_yasea_flv_SrsFlv_setAudioTrack
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     net_ossrs_yasea_flv_SrsFlv
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_ossrs_yasea_flv_SrsFlv_init
  (JNIEnv *, jobject);

/*
 * Class:     net_ossrs_yasea_flv_SrsFlv
 * Method:    writeAudioSample
 * Signature: (Ljava/nio/ByteBuffer;IIJI)V
 */
JNIEXPORT void JNICALL Java_net_ossrs_yasea_flv_SrsFlv_writeAudioSample
  (JNIEnv *, jobject, jobject, jint, jint, jlong, jint);

/*
 * Class:     net_ossrs_yasea_flv_SrsFlv
 * Method:    writeVideoSample
 * Signature: (Ljava/nio/ByteBuffer;IIJI)V
 */
JNIEXPORT void JNICALL Java_net_ossrs_yasea_flv_SrsFlv_writeVideoSample
  (JNIEnv *, jobject, jobject, jint, jint, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
