package com.vgaw.generate;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.id
     *
     * @mbggenerated Sun May 22 22:08:14 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.token
     *
     * @mbggenerated Sun May 22 22:08:14 CST 2016
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.name
     *
     * @mbggenerated Sun May 22 22:08:14 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.password
     *
     * @mbggenerated Sun May 22 22:08:14 CST 2016
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.id
     *
     * @return the value of v_user.id
     *
     * @mbggenerated Sun May 22 22:08:14 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.id
     *
     * @param id the value for v_user.id
     *
     * @mbggenerated Sun May 22 22:08:14 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.token
     *
     * @return the value of v_user.token
     *
     * @mbggenerated Sun May 22 22:08:14 CST 2016
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.token
     *
     * @param token the value for v_user.token
     *
     * @mbggenerated Sun May 22 22:08:14 CST 2016
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.name
     *
     * @return the value of v_user.name
     *
     * @mbggenerated Sun May 22 22:08:14 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.name
     *
     * @param name the value for v_user.name
     *
     * @mbggenerated Sun May 22 22:08:14 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.password
     *
     * @return the value of v_user.password
     *
     * @mbggenerated Sun May 22 22:08:14 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.password
     *
     * @param password the value for v_user.password
     *
     * @mbggenerated Sun May 22 22:08:14 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}